### ISSUE TITLE
Window doesn't resize properly after minimizing

### ISSUE THREAD

**Issue by steffen-wilke** [weisJ/darklaf#149] opened 2020-04-23 23:05 UTC
**Describe the bug**
When minimizing a window with enabled decorations, the widow doesn't resize properly when maximizing if from a minimized state. 

Seems like there's some negative inset. This is true for all directions of the window.

**To Reproduce**

1. Have a window with decorations.
2. Maximize the window
3. Minimize the window
4. Maximize it again

**Screenshots**
Note: the screenshots are taken from the top left corner of my screen.

Normal:
![normal](https://user-images.githubusercontent.com/7015370/80157767-32790700-85c7-11ea-8d63-665104bd0d69.png)

After minimizing:
![after minimizing](https://user-images.githubusercontent.com/7015370/80157778-386ee800-85c7-11ea-8b4e-27e42ad5a51b.png)

**Additional Information:**
- OS: Windows 10 Pro
- OS Version: 10.0.18363 Build 18363
- Darklaf Version: 2.0.3

**Comment by weisJ** [comment] 2020-04-25 14:54
Fixed in dd19ad4e66d5d5f8210745327f810b3710ddc91c.
Though there is some minor issue which I cannot really find the cause of:
1. Maximize the window by `windows + arrow_up`.
2. Snap the window to the left or right by `windows + arrow_[left, right]`.

This will result the window not being properly snapped every second time.
This is only really noticeable in a multi-monitor setup. In this case the window will be slightly misplaced and spill over to the other monitor. 

Snapping it a second time (i.e. repeating `windows + arrow_[left, right]`) will position it properly. For now I figure this isn't a big issue.

**Closed by weisJ** 2020-04-25 14:54 UTC
Labels: bug, windows
