### ISSUE TITLE
Add the ability to set the default font and change it in ThemeSettings

### ISSUE THREAD

**Issue by Xujiayao** [weisJ/darklaf#303] opened 2022-01-11 17:17 UTC
I couldn't find a method in Darklaf to set the default font (the default font of Windows Darklaf is not designed for Chinese), so I used the following code and it works:

```java
setDefaultFont(new FontUIResource(new Font("Microsoft YaHei", Font.PLAIN, 12)));

public static void setDefaultFont(FontUIResource defaultFont) {
	Enumeration<Object> keys = UIManager.getDefaults().keys();
	while (keys.hasMoreElements()) {
		Object key = keys.nextElement();
		Object value = UIManager.get(key);
		if (value instanceof FontUIResource)
			UIManager.put(key, defaultFont);
	}
}
```

However, after using the above code, the Font Size Settings of ThemeSettings no longer works (tried Apply and OK).

Another problem is that when I use the `Locale.setDefault()` method to set the Locale to a different language (e.g. English, Japanese), the ThemeSettings panel is still the default language used by the system (Chinese).

Maybe you can write a method that sets the default font and add it to ThemeSettings :)

| After using the code  | Normal situation |
| ----------------------- | ------------------- |
| ![image](https://user-images.githubusercontent.com/58985541/148988647-b3d49a12-c74a-4e3d-8e1a-a9604007b86b.png)  | ![image](https://user-images.githubusercontent.com/58985541/148989300-d9c3a0bf-7061-488f-9af8-d96dce807b2a.png)  |

**Comment by weisJ** [comment] 2022-01-11 17:44
This sounds like a reasonable feature :)

**Comment by weisJ** [comment] 2022-02-06 14:39
> Another problem is that when I use the Locale.setDefault() method to set the Locale to a different language (e.g. English, Japanese), the ThemeSettings panel is still the default language used by the system (Chinese).

There is no way to detect a changed locale automatically. You'll have to invalidate the ui manually. You can call `LafManager.updateLaf()` to do this.

**Comment by Xujiayao** [comment] 2022-02-06 15:15
OK, I'll try it later.

**Comment by Xujiayao** [comment] 2022-02-07 14:56
> > Another problem is that when I use the Locale.setDefault() method to set the Locale to a different language (e.g. English, Japanese), the ThemeSettings panel is still the default language used by the system (Chinese).
> 
> There is no way to detect a changed locale automatically. You'll have to invalidate the ui manually. You can call `LafManager.updateLaf()` to do this.

I remember when I posted this issue, it couldn't set the locale to a different language, but I don't seem to need to use `LafManager.updateLaf()` to set the locale to a different language now. It may have been fixed.

```java
public static void main(String[] args) {
	SwingUtilities.invokeLater(() -> {
		LafManager.install(new DarculaTheme());
		Locale.setDefault(Locale.JAPANESE);

		JFrame frame = new JFrame("Darklaf - A themeable LaF for Swing");
		frame.setSize(600, 400);

		JButton button = new JButton("Click here!");

		JPanel content = new JPanel();
		content.add(button);

		frame.setLocationRelativeTo(null);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setContentPane(content);
		frame.setVisible(true);

		button.addActionListener(e -> {
			ThemeSettings.showSettingsDialog(null);
		});
	});
}
```

**Comment by weisJ** [comment] 2022-02-07 17:13
The issue should arise if you change the locale after the settings have already been opened once.

**Comment by Xujiayao** [comment] 2022-02-08 03:20
Button click order: `1 -> 2 -> 3 -> 1` & `2 -> 3 -> 1`

It seems that `LafManager.updateLaf()` doesn't work, and the same problem occurs whether ThemeSettings is opened once or not.

![image](https://user-images.githubusercontent.com/58985541/152910983-7b345398-d5d6-4b7a-b43d-901704a8b957.png)

```java
LafManager.install(new DarculaTheme());

// The same problem occurs regardless of whether this line appears or not
Locale.setDefault(Locale.ENGLISH);

...

button1.addActionListener(e -> {
	ThemeSettings.showSettingsDialog(null);
});

button2.addActionListener(e -> {
	Locale.setDefault(Locale.JAPANESE);
});

button3.addActionListener(e -> {
	LafManager.updateLaf();
});
```

**Comment by weisJ** [comment] 2022-02-11 20:18
Ah the issue is that the laf has to actually be updated for the text to change. You can force this to happen by calling:
````java
LafManager.installTheme(LafManager.getInstalledTheme().copy());
````
Currently this will print a warning message. Feel free to ignore it for now. I'll provide a better method to accomplish this without the message appearing.

**Comment by weisJ** [comment] 2022-02-11 20:53
With the latest snapshot you are able to provide a prototype font:
````java
LafManager.registerDefaultsAdjustmentTask((theme, props) -> {
    props.put("theme.fontPrototype", new Font("Microsoft YaHei", Font.PLAIN, 12));
});
Note that the font size is irrelevant and won't affect the size of other fonts. For this the font size in the theme settings is still the relevant authority. 

I know this isn't exactly what you had in mind, but until I can provide a nice looking way to select the font I think this will at least solve your problem at hand.
````

**Comment by Xujiayao** [comment] 2022-02-12 14:25
Thanks! I'll test these new features tomorrow.

**Comment by Xujiayao** [comment] 2022-02-13 08:55
Thank you! I just tested and both work.

I found a new problem while testing:

The font size of the title bar is reduced. However, if I enter the ThemeSettings Dialog to adjust the font to another size, click Apply, and then adjust it back to 100%, click Apply again, the font size will return to normal.

| Before | After |
| ----------------------- | ------------------- |
| ![image](https://user-images.githubusercontent.com/58985541/153745782-16657fa8-b7c4-4454-ba08-ea3ae58bc32a.png)  | ![image](https://user-images.githubusercontent.com/58985541/153745791-17036a74-f0ca-4777-afe2-b52de0995512.png)  |

**Comment by weisJ** [comment] 2022-02-13 16:14
The fact that the font got bigger after changign the size is the actuall issue here. It actually should always be as in the "Before" iamge (if default font size is selected). Fixed in 36393697725bcea5947562bede66964bc098b552

**Comment by Xujiayao** [comment] 2022-02-14 05:45
I just tried it and now the default size is the same as the "After" of the previous comment, which is the correct default size.

However, the following code to set the font does not work for the title bar:

![image](https://user-images.githubusercontent.com/58985541/153806608-c83ea2d6-915f-4b99-b462-4ea3b843eefa.png)

After repeating the same operation as the previous comment, the font becomes the correct `Microsoft YaHei`.

![image](https://user-images.githubusercontent.com/58985541/153806810-7d47262e-80bf-49b4-a5d0-9180a5c508e5.png)

````java
LafManager.registerDefaultsAdjustmentTask((theme, props) -> {
     props.put("theme.fontPrototype", new Font("Microsoft YaHei", Font.PLAIN, 12));
});
````

**Comment by weisJ** [comment] 2022-02-14 12:42
Fixed in 0ad6d04ffae2b82a271de5845fea8526fcee9589

**Comment by Xujiayao** [comment] 2022-02-14 14:01
Thank you!

**Comment by weisJ** [comment] 2022-02-15 14:40
I’m hesitating whether it should be possible to change the font through the theme settings. There isn’t a guarantee that a theme works with all fonts. Also applications would need to make sure they work with different fonts.

Of course I could make the settings dialog configurable to enable/disable the font chooser individually, but that is adding unnecessary complexity. 

I’d rather try to tackle to specific problem you are trying to solve i.e. the default fallback font for Chinese characters looks rather ugly.

**Comment by Xujiayao** [comment] 2022-02-15 15:41
![image](https://user-images.githubusercontent.com/58985541/154094580-5a350522-1f55-4217-adae-c0efdab943e2.png)

I'm not sure how JetBrains implements this feature?

Maybe the last option is easier. I think the default and best font for Simplified Chinese system should be "Microsoft YaHei" (not 100% sure). I think a method similar in function to setting `theme.fontPrototype` is a good solution and can be kept.

**Comment by weisJ** [comment] 2022-02-16 21:23
Ok I have done the following:
- On Windows if the Locale is set to a language with youses chinese scripts "Microsoft YaHei" is now the default font.
- The font prototype feature remains. It is now promoted to aproper API in `Theme` and `ThemeSettings`. (This means the `theme.fontPrototype` property doesn't do anything anymore).
- In the settings one can choose a custom font (similar to above). The search functionality is subpar comapred to Jetbrains but I think it should be possible to replicate the behaviour (in the future).

**Comment by Xujiayao** [comment] 2022-02-17 03:32
OK! I have to deal with the outbreak in Hong Kong in the next few days so I don't have time to check out these new features. I'll test them later, thank you!

**Comment by Xujiayao** [comment] 2022-02-25 02:58
Thank you so much!

This perfectly solves my needs! I think this issue can be closed now.
By the way, it seems that the content in README.md needs to be updated?

**Comment by weisJ** [comment] 2022-02-26 20:32
> By the way, it seems that the content in README.md needs to be updated?

What content of the README are you referring to explicitely?

**Comment by Xujiayao** [comment] 2022-02-28 02:22
It's still in 2.7.2, and the new features of ThemeSettings haven't been added yet?

**Closed** 2022-04-05 05:47 UTC
Labels: enhancement
