### ISSUE TITLE
[JComboBox] Incorrect popup location on high dpi screens.

### ISSUE THREAD

**Issue by Ilolka1337** [weisJ/darklaf#162] opened 2020-05-04 06:31 UTC
**Screenshots**
![image](https://user-images.githubusercontent.com/63341162/80940955-cd54bb00-8de9-11ea-898b-7ec1dbedfc7c.png)

**Additional Information:**
 - OS: [Win]
 - OS Version: [10]
- Darklaf Version: [2.1.1]

**Additional context**
I have only 5 ComboBoxes, I switch one of them and the topic starts to shift visually

**Comment by weisJ** [comment] 2020-05-04 06:41
Please provide a proper description of what you expect to happen and what’s happening instead.

Without more context the screenshot isn’t telling me anything. Also please provide a minimal example to reproduce.

**Comment by Ilolka1337** [comment] 2020-05-04 07:28
@weisJ i can but only later and apparently this problem is relevant only for 4K monitors

**Comment by Ilolka1337** [comment] 2020-05-04 16:55
@weisJ 
[23.zip](https://github.com/weisJ/darklaf/files/4576007/23.zip)
that’s all i run and this problem is still there

**Comment by weisJ** [comment] 2020-05-04 17:35
I have added the code to your comment. Please refrain from uploading code as a zip archive if it's only two files.

Also I still don't know what issue you are exactly encountering. The program works fine for me (aside from the weird choice of layout) and your screenshot doesn't give me any context.

**Comment by Ilolka1337** [comment] 2020-05-04 17:41
![image](https://user-images.githubusercontent.com/63341162/80995887-a331e600-8e47-11ea-84f1-be3477201e90.png)

**Comment by Ilolka1337** [comment] 2020-05-04 17:43
![image](https://user-images.githubusercontent.com/63341162/80996114-f73cca80-8e47-11ea-8361-67dfde81e188.png)

**Comment by Ilolka1337** [comment] 2020-05-04 17:44
@weisJ i do not know how to explain it

**Comment by Ilolka1337** [comment] 2020-05-04 17:45
@weisJ i can try to record a video

**Comment by weisJ** [comment] 2020-05-04 17:47
>apparently this problem is relevant only for 4K monitors

What is your resolution exactly? Do you use windows scaling. Which java version do you use? How many monitors do you use?

**Comment by Ilolka1337** [comment] 2020-05-04 17:57
What is your resolution exactly? - Display: 3840x2280
Do you use Windows screen scaling? - default(recommended)
Which java version do you use? - Java version: 1.8.0_202
How many monitors do you use? - maybe this problem is only on 4K I tested on my 1920x1080 there was nothing

**Comment by weisJ** [comment] 2020-05-04 17:59
> What is your resolution exactly? - Display: 3840x2280
> Do you use Windows screen scaling? - default(recommended)

Now I'm just interested how big the monitor is. Usually windows recommends `150%-200%` for resolutions that big. What is the dpi of the monitor.

> Which java version do you use? - Java version: 1.8.0_202

Please try with Java >=9

> How many monitors do you use? - maybe this problem is only on 4K I tested on my 1920x1080 there was nothing

I meant how many at the same time.

**Comment by Ilolka1337** [comment] 2020-05-04 18:02
@weisJ i can’t test this in Java 9, it causes blur in all applications

**Comment by Ilolka1337** [comment] 2020-05-04 18:03
How many monitors do you use? - 3 monitors

**Comment by weisJ** [comment] 2020-05-04 18:05
> How many monitors do you use? - 3 monitors

Can you try using only the 4k monitor.

> i can’t test this in Java 9, it causes blur in all applications

That's very strange and increases my suspicion that this isn't actually a darklaf issue.
Why do I think that:
- The calculation of the popup location isn't even done by darklaf.
- Java 8 doesn't support proper ui scaling and has no official high dpi support.

**Comment by Ilolka1337** [comment] 2020-05-04 18:09
can you try using only the 4k monitor. - in the morning I tested and so and so / result: nothing

in the morning i tested setDecorations, this fixed the problem only with the decorations turned off

**Comment by weisJ** [comment] 2020-05-04 18:10
> in the morning i tested setDecorations, this fixed the problem only with the decorations turned off

Please clarify. Do enabled or disabled decorations produce the error?

**Comment by Ilolka1337** [comment] 2020-05-04 18:11
@weisJ Please clarify. Do enabled or disabled decorations produce the error? - when enabled

**Comment by weisJ** [comment] 2020-05-05 16:20
> > How many monitors do you use? - 3 monitors
> 
> Can you try using only the 4k monitor.
> 
> > i can’t test this in Java 9, it causes blur in all applications
> 
> That's very strange and increases my suspicion that this isn't actually a darklaf issue.
> Why do I think that:
> 
> * The calculation of the popup location isn't even done by darklaf.
> * Java 8 doesn't support proper ui scaling and has no official high dpi support.

Please try with only the 4k monitor connected and with Java 9 (ignore the fact that its's blurry).

> Do you use Windows screen scaling? - default(recommended)

What value is actually recommended to you? is it 100% (most likely it isn't)
Did you change any settings for java to override the system scaling? i.e.
`java.exe` -> Properties -> Compatibility -> Change high DPI settings

**Comment by Ilolka1337** [comment] 2020-05-06 03:29
@weisJ 
> Please try with only the 4k monitor connected and with Java 9 (ignore the fact that its's blurry).

no changes

> What value is actually recommended to you? is it 100% (most likely it isn't)

300% - 350%

as I wrote to you, this problem only appears when `setDecorationsEnabled(true)`

@weisJ maybe problem in decorations? because as I wrote with the decorations disabled, there is no such problem

I hope you can fix it for a 4k monitor

**Comment by weisJ** [comment] 2020-05-06 14:26
Did you try java 9? Do you have any overridden settings for dpi scaling.
Do you also experience the issue if you simply use a single combo box centred in the frame (e.g. by using a `GridBagLayout` with null constraints)?

It’s really important that you answer all the questions as otherwise I can’t do anything about the issue. I have a monitor with  a resolution of `3000 x 2000` myself an don’t experience any issues (regardless of system scaling) that’s why I need more context in order to reproduce the issue.

**Comment by Ilolka1337** [comment] 2020-05-09 12:21
@weisJ 
Actually, I get this with the very programs where setDecorationsEnabled(true) is set
I think this problem can only be caused on some systems
I checked in Java 9 the same thing
![image](https://user-images.githubusercontent.com/63341162/81473565-fd47f800-9207-11ea-8aa6-3592a0ff99d5.png)

**Comment by Ilolka1337** [comment] 2020-05-09 12:24
@weisJ this is how the GraxCode application works for me
![image](https://user-images.githubusercontent.com/63341162/81473709-f968a580-9208-11ea-94f5-9270cf532824.png)

**Comment by Ilolka1337** [comment] 2020-05-09 12:30
@weisJ 
this problem cannot be described; you must see it yourself
this problem is only in darklaf all i can tell you

**Comment by weisJ** [comment] 2020-05-10 10:42
Please answer all my questions:
>Did you change any settings for java to override the system scaling? i.e.
java.exe -> Properties -> Compatibility -> Change high DPI settings

As long as I can't reproduce the issue I won't be able to da anything about it as much as I'd like to. But without confirmation that it is actually directly related to darklaf and not caused by any other changes on your side I don't think I can actually do something.

**Comment by Ilolka1337** [comment] 2020-05-12 09:55
@weisJ 
> Did you change any settings for java to override the system scaling? i.e.
> java.exe -> Properties -> Compatibility -> Change high DPI settings

I have everything by default

> As long as I can't reproduce the issue I won't be able to da anything about it as much as I'd like to. But without confirmation that it is actually directly related to darklaf and not caused by any other changes on your side I don't think I can actually do something.

I did not change anything in windows after installation, I have no problems with themes other than darklaf

**Comment by weisJ** [comment] 2020-05-12 11:54
Please feel free to build darklaf locally and check if you can find the issue. My first assessment would be that the issue would be somewhere in [`Decorations.cpp`](https://github.com/weisJ/darklaf/blob/master/windows/src/main/cpp/Decorations.cpp). You can try to disable some parts of the window procedure or the decorations installation to see if the issue persists. If you have any questions on what the code does feel free to ask me and I'll try to clarify.

I can't possibly offer a solution without being able to reproduce the issue.

**Comment by Ilolka1337** [comment] 2020-05-12 14:49
@weisJ 
I don’t know well c++, maybe you will just send libraries that I will have to test?

**Comment by weisJ** [comment] 2020-05-13 12:11
You don’t need to know any c++ only a compiler. If you don’t have any installed currently I recommend using the [Visual Studio command line tools](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019).

Some things you can try:
- Disable Installation of decorations by commenting out the [`InstallDecorations`](https://github.com/weisJ/darklaf/blob/1287a9c436f51f73474706617cbc42b27615964c/windows/src/main/cpp/Decorations.cpp#L273)

- Comment out any combination of cases in the [switch of the window procedure](https://github.com/weisJ/darklaf/blob/1287a9c436f51f73474706617cbc42b27615964c/windows/src/main/cpp/Decorations.cpp#L302).

I won’t send you any libraries as it’s a huge effort to do “remote debugging” of this kind.

**Comment by weisJ** [comment] 2020-05-17 13:09
I think I could isolate a scenario where I can reproduce the issue. Currently working on a fix.

**Comment by weisJ** [comment] 2020-05-17 14:39
Please try the current repository version.

**Comment by Ilolka1337** [comment] 2020-05-20 01:36
@weisJ same

**Comment by Ilolka1337** [comment] 2020-05-20 02:07
```
[34m[2020-05-20 05:05:41][33m [WARNING][0m[33m Could not load color with id'Windows.Icons.windowCloseHover.color' fallbacks[] Using color java.awt.Color[r=255,g=0,b=0] instead.[0m[01m [at com.github.weisj.darklaf.icons.IconColorMapper][2m[0m
[34m[2020-05-20 05:05:41][33m [WARNING][0m[33m Could not load color with id'Windows.Icons.windowCloseHover.color' fallbacks[] Using color java.awt.Color[r=255,g=0,b=0] instead.[0m[01m [at com.github.weisj.darklaf.icons.IconColorMapper][2m[0m
```

**Comment by weisJ** [comment] 2020-05-20 06:46
Are you sure you are running an up to date version? Does the message get printed every time?

**Comment by Ilolka1337** [comment] 2020-05-26 05:24
@weisJ 
well damn, I liked darklaf so much, but on some systems it seems to be broken in that the application interface starts to fly inside the application

**Comment by Ilolka1337** [comment] 2020-05-26 05:25
@weisJ 
How can I help you fix this problem?

**Comment by Ilolka1337** [comment] 2020-05-26 05:44
@weisJ 
I recorded a video so you can look at this problem
https://mega.nz/file/PuAhBYjK#MGC-euIl_ty86a9DsmDzpQBCXz0pcc-dOOmi0p1Uiz4

**Comment by weisJ** [comment] 2020-05-26 07:08
Thank you very much for the video.

> How can I help you fix this problem?

The first step would be to try to reproduce the issue on a different machine. Do you have access to another Windows machine which you could try with your monitor?

Generally you can always try the current master branch using:
- Build darklaf:
   ````
   git clone https://github.com/weisJ/darklaf.git
   cd darklaf
   gradlew build
   ````
   If you don't have a c++ toolchain installed (or the build fails while building the native binaries) you can download the [latest binary](https://github.com/weisJ/darklaf/actions?query=workflow%3A%22Build+Native+Libraries%22) in the correct loactions
   - `libdarklaf-macos.dylib` -> `macos/libraries/macos-x86-64/`
   - `darklaf-windows_x86-64.dll` -> `windows/libraries/windowx-x86-64`
   - `darklaf-windows_x86.dll` -> `windows/libraries/windowx-x86`
- Run the demos. e.g. for the combo box demo run:
  ````
  gradlew runDemo --class ui.comboBox.ComboBoxDemo
  ````
  You can add your own code into `core/test/java/` and run it using
  ````
  gradlew runDemo --class <qualified path to your class>
  ````

**Comment by Ilolka1337** [comment] 2020-05-26 14:16
@weisJ 

> The first step would be to try to reproduce the issue on a different machine. Do you have access to another Windows machine which you could try with your monitor?

no, but I checked in a virtual machine this problem is unlikely in the computer

**Comment by Ilolka1337** [comment] 2020-05-26 14:27
@weisJ 
video with comboboxdemo
https://mega.nz/file/O3JiBaBT#6ttRPQf6JWY7jSRvEB1CoDbhPDzFZe-mmj2LTs24DZ4

**Comment by Ilolka1337** [comment] 2020-05-26 14:47
@weisJ 
for some reason, everything is fine only with buttondemo
https://mega.nz/file/3qZyXY5L#F6bI0FNyflNlLqgDWQQ9NVuMjFWzPuUtMbEnAuORnuM

**Comment by weisJ** [comment] 2020-05-27 11:46
Could you please try the the latest revision? You'll need to re-download the latest binaries if you aren't compiling them yourself.

**Comment by weisJ** [comment] 2020-05-27 11:49
@Ilolka1337 I am closing this issue and moving the topic to #172 as the paint bleeding is a separate issue.

**Closed by weisJ** 2020-05-27 11:49 UTC
Labels: bug, windows
