### ISSUE TITLE
filechooser: place list and detail buttons together without gap

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#96] opened 2020-03-18 20:22 UTC
It would be great if toggle buttons were side by side, so the connected corners should not be round.

darklaf:
<img width="167" alt="darklaf" src="https://user-images.githubusercontent.com/213894/77003865-2d44ee80-696f-11ea-92fd-b0d1415813c3.png">

macOS:
<img width="331" alt="radio in toolbar" src="https://user-images.githubusercontent.com/213894/77002842-42208280-696d-11ea-8bca-ddbe5184805d.png">

**Comment by weisJ** [comment] 2020-03-19 11:42
They are now together though sacrificing the focus border (they are still focusable its just not painted) as it looks odd with the cut off border. To have the toolbar look coherent I disabled the focus painting for the other three buttons as well.

**Comment by weisJ** [comment] 2020-03-19 12:21
They icon colours are now adjusted for better contrast when the button is selected.

**Comment by vlsi** [comment] 2020-03-19 21:20
> they are still focusable its just not painted

Please, please, never do that. Focusable items must have the border. That is like the first rule of accessibility.

Otherwise, it is hard to tell what would happen if the user presses `space`.

Sample W3C recommendation: https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html
They explicitly mention that removal of the focus border is a violation:
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/F78

Of course, it would be great if the focus border was painted overlayed on top of the second button, however, I'm not sure how complicated that is in Swing.

So I would suggest two options:
a) Paint focus as `top, left, bottom` and consider it as a known bug (e.g. for later resolution)
b) Paint the focus somehow over the button
For instance:
<img width="125" alt="Снимок экрана 2020-03-20 в 0 18 51" src="https://user-images.githubusercontent.com/213894/77116014-71ec8a80-6a40-11ea-9469-f2786dee878c.png">
<img width="123" alt="Снимок экрана 2020-03-20 в 0 18 56" src="https://user-images.githubusercontent.com/213894/77116022-74e77b00-6a40-11ea-8715-93e0d1470803.png">
c) Make the buttons non-focuseable

**Comment by weisJ** [comment] 2020-03-19 22:58
Thank you for pointing that out. I'll definitely change it. Preferably I'd like a solution that actually provides a focus indicator, as otherwise every button that uses this feature would need to be made non-focusable.

**Comment by weisJ** [comment] 2020-03-20 15:22
They are focus painted again as of 6b2067dbb9fcb11fe8ef1dcb1cf4a76229380342.
Also ce9715df807e3267749c0826815f7ce164948d05 fixes the painting for the focus border in a way that I thing is the most consistent.

**Comment by vlsi** [comment] 2020-03-20 15:45
> Also ce9715d fixes the painting for the focus border in a way that I thing is the most consistent

I think the border should not overly on top of the button.
I might cover the sibling button, but it should not cover the current one.

**Comment by vlsi** [comment] 2020-03-20 15:46
<img width="208" alt="Снимок экрана 2020-03-20 в 18 45 29" src="https://user-images.githubusercontent.com/213894/77180456-00154f00-6adb-11ea-969a-936debe1f6f7.png">

The left margin on the menu looks odd. The one without icons seems to have a too small margin.

**Comment by vlsi** [comment] 2020-03-20 15:48
> They are focus painted again

For some reason, `non-selected` button is not really focuseable.
In other words, I can't flip between list vs details by using keyboard only.

**Comment by weisJ** [comment] 2020-03-20 18:22
> I might cover the sibling button, but it should not cover the current one.

Overlapping sibling buttons is non-trivial without giving the button more context on what it's siblings are.

> In other words, I can't flip between list vs details by using keyboard only.

Apparently the issue was adding the buttons to a `ButtonGroup`. I have now manually added the necessary listeners to ensure only one is selected at a time but that should only be a temporary solution until I know what exactly caused the issue. I guess there is some funky business going on in `LayoutFocusTraversalPolicy#accept`.

**Comment by vlsi** [comment] 2020-03-20 18:26
> Apparently the issue was adding the buttons to a ButtonGroup

Well. I did try removing the ButtonGroup, and it did work. However, I gave up near `LayoutFocusTraversalPolicy` as well :-/

**Comment by vlsi** [comment] 2020-03-20 18:27
>Overlapping sibling buttons is non-trivial without giving the button more context on what it's siblings are.

What if the focus border is always painted around the button?  Do you mean it would go "under" the button?
Can it be painted as a tooltip (== on top of the buttons)?

**Comment by weisJ** [comment] 2020-03-20 18:29
> The left margin on the menu looks odd. The one without icons seems to have a too small margin.

I have added a new default padding for the left side in case no item has an icon. Should look more consistent now.

**Comment by weisJ** [comment] 2020-03-20 18:33
> What if the focus border is always painted around the button? Do you mean it would go "under" the button?

Basically that is what would happen. One would need to adjust the the z-order of all components that could possibly obscure the button (i.e. everything component of the parent) but this really shouldn't be done as it messes with things the user might have set (even though setting z-orders should really only be set by layout managers).

> Can it be painted as a tooltip (== on top of the buttons)?

Sounds like an extremely expensive operation for nice borders.

My solution would be (though more setup for using the grouped buttons is needed) is to tell the button what its neighbours are and let the neighbouring buttons paint the missing part of the border.

**Comment by vlsi** [comment] 2020-03-20 18:33
ad4e43edbc7742a63582fc661af949570d2b9d74 looks good to me:

<img width="496" alt="Снимок экрана 2020-03-20 в 21 32 11" src="https://user-images.githubusercontent.com/213894/77195308-770a1200-6af2-11ea-8ee5-c84211410ae3.png">

**Comment by weisJ** [comment] 2020-03-20 19:07
8607de39400a70292aa037c29e21e3db4ead59a5 implements the above approach (Not yet for filechooser). Though setup is a lot more difficult now (see `GroupedButtonDemo`)

**Comment by weisJ** [comment] 2020-03-20 21:32
Relevant jdk bug: https://bugs.openjdk.java.net/browse/JDK-8130893
It is marked as `not an issue` with the comment that the industry standard for a button-group is that tab should only move into or out of a group. Navigation inside the group should use the arrow keys.
Then another issue is linked where this originally was decided:
https://bugs.openjdk.java.net/browse/JDK-8033699

But it __only__ works for `JRadioButton`.

This is the commit that fixes it for RadioButtons. 
http://hg.openjdk.java.net/jdk7u/jdk7u/jdk/rev/84c3e31f3c4a
The problem is that it only expects a `JRadioButton` to be a valid focus target.

I guess the solution is to port this fix to `JCheckBox` and `JToggleButton`.

**Comment by weisJ** [comment] 2020-03-23 10:45
I’m closing this and created #116 for the focus issue.

**Closed** 2020-03-23 10:45 UTC
Labels: enhancement
