### ISSUE TITLE
incorrect defaultButton behavior in JDialogs and JOptionPanes

### ISSUE THREAD

**Issue by MioBlanco** [weisJ/darklaf#117] opened 2020-03-23 11:21 UTC
![vN6WukMCGN](https://user-images.githubusercontent.com/56546322/77309586-30d4ce80-6cfd-11ea-9f16-bbf8f3fd351e.gif)

**JDialog**
When you have a dialog with 2 or more Buttons and the second button is set as the default button, the first button will get the focusBorder, even thoe the second button is showing as default (blue background).
Furthermore when switching the focus with "Tab" the border will always be in the correct place, but when hitting "Enter" it will **always** run the default buttons action.

**JOptionPane**
The initial button and focusborder is correct here, but same with the focuschange, the border will display correct, but "Enter" will allways hit yes.

Here's my code if u want to test it by yourself
````java
public class Test
{
  public static void main( String[] args )
  {
    LafManager.install(); //For default theme (IntelliJ)
    LafManager.install( new DarculaTheme() ); //Specify the used theme.
    JFrame frame = new JFrame();
    JPanel mainPanel = new JPanel();
    JButton dialogButton = new JButton( "Open JDialog" );
    JButton joptionButton = new JButton( "Open JOptionPane" );
    joptionButton.addActionListener( new ActionListener()
    {
      @Override
      public void actionPerformed( ActionEvent e )
      {
        int answer = JOptionPane.showConfirmDialog( frame, "Choose wisely", "OptionPane", JOptionPane.YES_NO_CANCEL_OPTION );
        if ( answer == JOptionPane.YES_OPTION )
        {
          System.out.println( "Pressed YES" );
        }
        else if ( answer == JOptionPane.NO_OPTION )
        {
          System.out.println( "Pressed NO" );
        }
        else
        {
          System.out.println( "Pressed CANCEL" );
        }
      }
    } );
    dialogButton.addActionListener( new ActionListener()
    {

      @Override
      public void actionPerformed( ActionEvent e )
      {
        JDialog dialog = new JDialog( frame );
        dialog.setVisible( true );
        dialog.setLayout( new FlowLayout() );
        JButton button1 = new JButton( "Button1" );
        JButton button2 = new JButton( "Button2" );
        button1.addActionListener( new ActionListener()
        {
          @Override
          public void actionPerformed( ActionEvent e )
          {
            System.out.println( "Button1" );
          }
        } );
        button2.addActionListener( new ActionListener()
        {

          @Override
          public void actionPerformed( ActionEvent e )
          {
            System.out.println( "Button2" );
          }
        } );
        dialog.add( button1 );
        dialog.add( button2 );
        dialog.setModal( true );
        dialog.getRootPane().setDefaultButton( button2 );
        dialog.pack();
        dialog.setLocationRelativeTo( frame );
        dialog.setVisible( true );
      }
    } );
    mainPanel.add( dialogButton );
    mainPanel.add( joptionButton );
    frame.add( mainPanel );
    frame.pack();
    frame.setSize( new Dimension( frame.getWidth() + 30, frame.getHeight() + 30 ) );
    frame.setLocationRelativeTo( null );
    frame.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
    frame.setVisible( true );
  }
}
````

**Comment by weisJ** [comment] 2020-03-23 11:34
>... the first button will get the focusBorder, even thoe the second button is showing as default (blue background). ...

That is because it actually has the focus.


> ... but when hitting "Enter" it will **always** run the default buttons action. ...
> 

> ... but "Enter" will allways hit yes.

I think you are misunderstanding the focus subsystem. A focused button is invoked by pressing `space`. `enter` will **always** run the action of the default button.

—-

I’ll consider the first part as undesired behaviour but the second part won’t be fixed (as there is nothing to fix).

**Comment by MioBlanco** [comment] 2020-03-23 11:36
But when using IntelliJ "Enter" will actually trigger the action of the focused button.

**Comment by weisJ** [comment] 2020-03-23 12:04
The key point here is that changing this would result in a different focus behaviour for `JDialog`. It won’t be consistent anymore across the program. I could change the general keybinding to have `enter` always trigger the focused button (this would also need to be changed for checkboxes etc. which are also controlled by `space`). I don’t think that this would be a good idea:

1. Programs will behave different in darklaf than in other lafs. (Of course it already does so in certain places. But none of those are so essential as the focus system).

2. The point in having different keyboard triggers for the focused and the default button is that keyboard navigation time is reduced when trying to trigger the default key (i.e. in a panel with lots of buttons).

**Comment by Bios-Marcel** [comment] 2020-03-23 12:22
But Darklaf is the IntelliJ L&F and even IntelliJ behaves differently. Wouldn't it therefore be correct to act like IntelliJ does? To me it also seems more intuitive to not ignore the user-focus, since the user always expects the application to interact with the focused element or it's outer context if applicable. I'd deem the current behaviour to be wrong.

The keybinding for `space` must stay either way, this should be unrelated to what `enter` does in case of a focused button in a dialog.

If you need example, try for example deleting a project in IntelliJ. The resulting `JOptionPane` will respect your focus when hitting enter.

**Comment by vlsi** [comment] 2020-03-24 11:01
I just checked with IntelliJ 2020.1, macOS

They have the buttons in reverse: `enter` triggers the focused button, and `space` triggers the default one. I don't know if that depends on the shortcut settings or not.

At the same time, Chrome, Notes.app in macOS: `enter` triggers **default** button (which is consistent with Darklaf), and `space` triggers the focused one.

**Comment by vlsi** [comment] 2020-03-24 11:07
> To me it also seems more intuitive to not ignore the user-focus, since the user always expects the application to interact with the focused element or it's outer context if applicable

The user has two options:
* Perform the default action via pressing `enter` at any time. For instance, if you browse `open file` dialog, you don't need to navigate all the way to `open` button. You could just hit `enter` and trigger the default action.
* Trigger the focused action via pressing `space`. This is a corner-case, when the user wants to trigger a non-default action.

Frankly speaking, I would love to hear from IntelliJ team why did they flip `enter` vs `space` meaning.

**Comment by vlsi** [comment] 2020-03-24 11:19
>If you need example, try for example deleting a project in IntelliJ. The resulting JOptionPane will respect your focus when hitting enter.

Is it dialog-specific? Is it platform-specific?

I tried with `delete file`, and `enter` always performs the default action no matter what is focused.

**Comment by Bios-Marcel** [comment] 2020-03-24 11:47
Well, according to what you said, it seems that IntelliJ reacts differently on Mac OS and Windows. However, Darklaf doesn't do the same thing as IntelliJ, so something is weird for sure.

**Comment by vlsi** [comment] 2020-03-24 11:50
Well, IntelliJ discussion/tickets do not seem to be platform-specific: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000117550-Pressing-enter-always-does-the-blue-button-thing-not-the-highlighted-thing

**Comment by weisJ** [comment] 2020-03-24 11:56
The thing to point out here is that Darklaf doesn’t need to 100% match the behaviour of IntelliJ. Most notably I think it’s important that behaviour of programs is preserved where possible. A program that tries to be consistent with the rest of the os should not have this behaviour changed just because IntelliJ does it different as well.

I checked for chrome on Windows and there `enter` also triggers the focused button. So there is indeed something wrong but not in the sense that IntelliJ behaves different but that both behave wrong on some platform.

My suggestion would be to leave it as it is on macOS (as this seems to be the default there) and change it for Windows to follow the os convention.

**Comment by Bios-Marcel** [comment] 2020-03-24 14:06
Well, the thing is, that Darklaf changes the default windows behaviour. Open the environment variables dialog for example. The focus will be in the upper table and the default button is "okay", if you focus the "Cancel" Button and hit enter, it actually cancels. So darklaf is different from both my system and intellij.

**Comment by weisJ** [comment] 2020-03-24 17:12
My suggestion would be to leave it as it is on macOS (as this seems to be the default there) and change it for Windows to follow the os convention.

**Comment by Bios-Marcel** [comment] 2020-03-24 17:18
Agreed

**Comment by weisJ** [comment] 2020-03-25 20:42
I checked your example from the top and came to the conclusion that the button not being focused is not a bug. When using `JOptionPane` the default button always has the focus. When using a `JDialog` one is responsible for requesting the focus with the default button.

**Closed** 2020-03-25 21:03 UTC
Labels: enhancement
