### ISSUE TITLE
JTree rendering nodes where they should not be rendered

### ISSUE THREAD

**Issue by GraxCode** [weisJ/darklaf#158] opened 2020-04-30 22:54 UTC
**Describe the bug**
JTree nodes seem to be rendered, even when they shouldn't be visible on screen. First occured in 2.1.0, didn't happen on 2.0.3

**To Reproduce**
Don't know how to reproduce it, but you can take a look at threadtear. Seems to occur when another JFrame or JDialog is opened.

**Screenshots**
![Screenshot_6](https://user-images.githubusercontent.com/24767548/80766636-2b617400-8b46-11ea-8b57-22db349efe70.png)

**Additional Information:**
 - OS: Windows
 - OS Version: 10, 16299
- Darklaf Version: 2.1.0

**Comment by weisJ** [comment] 2020-05-01 10:35
Duplicate of #155

**Closed** 2020-05-01 15:15 UTC
Labels: bug, duplicate
